#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="src/arel tests"

set -x

${PREFIX}autoflake --in-place --recursive $SOURCE_FILES
${PREFIX}seed-isort-config --application-directories=arel
${PREFIX}isort --project=arel --recursive --apply $SOURCE_FILES
${PREFIX}black --target-version=py37 $SOURCE_FILES
