trigger:
  - master

pr:
  - master

variables:
  CI: true
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.cache/pip

jobs:
  - job: Check
    steps:
      - template: templates/install.yml
        parameters:
          pythonVersion: "3.8"

  - job: Test
    strategy:
      matrix:
        Python37:
          pythonVersion: "3.7"
        Python38:
          pythonVersion: "3.8"
          uploadCoverage: true

    steps:
      - template: templates/install.yml
        parameters:
          pythonVersion: $(pythonVersion)
      - script: scripts/test
        displayName: "Run tests"
      - script: |
          bash <(curl -s https://codecov.io/bash) -Z -C $(Build.SourceVersion)
        condition: eq(variables['uploadCoverage'], true)
        displayName: "Upload coverage"
